apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ola-mundo
  namespace: exemplo
spec:
  template:
    spec:
      containers:
        - image: kind.local/ola-mundo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
